#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROTO_DIR="$SCRIPT_DIR/../../proto"
OUT_DIR="$SCRIPT_DIR/kezen_test_cli/generated"

mkdir -p "$OUT_DIR"

python -m grpc_tools.protoc \
  -I "$PROTO_DIR" \
  --python_out="$OUT_DIR" \
  --grpc_python_out="$OUT_DIR" \
  "$PROTO_DIR/kezen.proto"

# Fix absolute imports generated by grpc_tools
if [[ "$OSTYPE" == "darwin"* ]]; then
  sed -i '' -e 's/import kezen_pb2 as kezen__pb2/from . import kezen_pb2 as kezen__pb2/g' "$OUT_DIR/kezen_pb2_grpc.py"
else
  sed -i -e 's/import kezen_pb2 as kezen__pb2/from . import kezen_pb2 as kezen__pb2/g' "$OUT_DIR/kezen_pb2_grpc.py"
fi

touch "$OUT_DIR/__init__.py"

echo "✅ Python gRPC stubs generated in $OUT_DIR"
