use std::fmt;
use std::net::SocketAddr;
use tokio::sync::{broadcast, mpsc};

use crate::engine::events::{EngineEvent, UserAction};

/// Additional access point types for an Agent.
///
/// Every Agent has exactly one implicit default access point (the parent node's MPSC channel).
/// This enum defines additionally mounted access points.
///
/// Every Event generated by the engine will be written to:
///   [Parent node MPSC (if any)] + [All additional access points listed here]
#[derive(Debug, Clone, PartialEq)]
pub enum AccessPoint {
    /// Local terminal TUI (ratatui).
    Tui { can_approve: bool },

    /// Classic text REPL (rustyline), a lightweight alternative to TUI.
    Repl { can_approve: bool },

    /// gRPC bidirectional streaming access point.
    Grpc { addr: SocketAddr, can_approve: bool },

    /// In-process MPSC channel (no network overhead).
    /// Used for in-process communication between parent and child Agents.
    InProcess,
}

impl AccessPoint {
    /// Whether this access point has approval authority.
    pub fn can_approve(&self) -> bool {
        match self {
            Self::Tui { can_approve } => *can_approve,
            Self::Repl { can_approve } => *can_approve,
            Self::Grpc { can_approve, .. } => *can_approve,
            Self::InProcess => false,
        }
    }

    /// A short type label for logging/display.
    pub fn kind_label(&self) -> &'static str {
        match self {
            Self::Tui { .. } => "TUI",
            Self::Repl { .. } => "REPL",
            Self::Grpc { .. } => "gRPC",
            Self::InProcess => "InProcess",
        }
    }
}

impl fmt::Display for AccessPoint {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Tui { can_approve } => write!(f, "TUI(approve={})", can_approve),
            Self::Repl { can_approve } => write!(f, "REPL(approve={})", can_approve),
            Self::Grpc { addr, can_approve } => {
                write!(f, "gRPC({}; approve={})", addr, can_approve)
            }
            Self::InProcess => write!(f, "InProcess"),
        }
    }
}

/// Runtime handle after an access point is started.
///
/// Holds:
///   - Copy of access point configuration (used to query `can_approve` etc.)
///   - `broadcast::Receiver<EngineEvent>` for this access point (automatically created by `event_tx.subscribe()`)
///   - `JoinHandle` of the spawned task, used for lifecycle management
pub struct AccessPointHandle {
    /// Access point configuration info (type + attributes).
    pub config: AccessPoint,
    /// tokio task handle for this access point.
    /// `None` if the access point has not been started or has been closed.
    pub task_handle: Option<tokio::task::JoinHandle<()>>,
}

impl AccessPointHandle {
    /// Checks if the task of this access point has terminated.
    pub fn is_finished(&self) -> bool {
        self.task_handle.as_ref().map_or(true, |h| h.is_finished())
    }

    /// Terminates this access point.
    pub fn abort(&mut self) {
        if let Some(h) = self.task_handle.take() {
            h.abort();
        }
    }
}

/// Starts an access point.
///
/// Starts the corresponding frontend service (gRPC server, etc.) based on the `AccessPoint` type.
/// Each access point receives:
///   - `event_rx`: Subscribed from the Gateway's event broadcast
///   - `action_tx`: Shared MPSC sender, UserAction from all access points merges into the same channel
///
/// # Returns
/// An `AccessPointHandle`, holding the spawned task handle.
///
/// # Note
/// TUI and REPL access points currently only log (they require exclusive terminal access, not suitable as passive Gateway access points).
/// gRPC access points will actually start the tonic server.
pub async fn start_access_point(
    ap: &AccessPoint,
    action_tx: mpsc::Sender<UserAction>,
    event_tx: broadcast::Sender<EngineEvent>,
) -> anyhow::Result<AccessPointHandle> {
    match ap {
        AccessPoint::Grpc { addr, can_approve } => {
            let addr = *addr;
            let can_approve = *can_approve;
            tracing::info!(%addr, can_approve, "Starting gRPC access point");

            let handle = tokio::spawn(async move {
                if let Err(e) =
                    crate::frontend::grpc::start_grpc_server(addr, action_tx, event_tx).await
                {
                    tracing::error!(%addr, error = %e, "gRPC access point failed");
                }
            });

            Ok(AccessPointHandle {
                config: ap.clone(),
                task_handle: Some(handle),
            })
        }
        AccessPoint::Tui { can_approve } | AccessPoint::Repl { can_approve } => {
            // Foreground access points (TUI / REPL) are managed by GatewayNode::run_foreground(), skip starting logic here.
            tracing::info!(
                can_approve,
                kind = ap.kind_label(),
                "Foreground access point registered (handled by run_foreground)"
            );
            Ok(AccessPointHandle {
                config: ap.clone(),
                task_handle: None,
            })
        }
        AccessPoint::InProcess => {
            // In-process channels do not require starting any additional services.
            Ok(AccessPointHandle {
                config: ap.clone(),
                task_handle: None,
            })
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tui_access_point_can_approve() {
        let ap = AccessPoint::Tui { can_approve: true };
        assert!(ap.can_approve());
    }

    #[test]
    fn repl_access_point_cannot_approve() {
        let ap = AccessPoint::Repl { can_approve: false };
        assert!(!ap.can_approve());
    }

    #[test]
    fn grpc_access_point_with_addr() {
        let ap = AccessPoint::Grpc {
            addr: "127.0.0.1:50052".parse().unwrap(),
            can_approve: true,
        };
        assert!(ap.can_approve());
        assert!(format!("{}", ap).contains("127.0.0.1:50052"));
    }

    #[test]
    fn in_process_cannot_approve() {
        let ap = AccessPoint::InProcess;
        assert!(!ap.can_approve());
    }

    #[test]
    fn display_formats_correctly() {
        let tui = AccessPoint::Tui { can_approve: true };
        assert_eq!(format!("{}", tui), "TUI(approve=true)");

        let repl = AccessPoint::Repl { can_approve: false };
        assert_eq!(format!("{}", repl), "REPL(approve=false)");
    }

    #[test]
    fn kind_label() {
        assert_eq!(AccessPoint::Tui { can_approve: true }.kind_label(), "TUI");
        assert_eq!(
            AccessPoint::Repl { can_approve: false }.kind_label(),
            "REPL"
        );
        assert_eq!(
            AccessPoint::Grpc {
                addr: "127.0.0.1:50052".parse().unwrap(),
                can_approve: true
            }
            .kind_label(),
            "gRPC"
        );
        assert_eq!(AccessPoint::InProcess.kind_label(), "InProcess");
    }

    #[test]
    fn access_point_handle_is_finished_when_no_task() {
        let handle = AccessPointHandle {
            config: AccessPoint::InProcess,
            task_handle: None,
        };
        assert!(handle.is_finished());
    }

    #[tokio::test]
    async fn access_point_handle_abort() {
        let task = tokio::spawn(async {
            // Long-running task
            tokio::time::sleep(tokio::time::Duration::from_secs(3600)).await;
        });
        let mut handle = AccessPointHandle {
            config: AccessPoint::InProcess,
            task_handle: Some(task),
        };
        assert!(!handle.is_finished());
        handle.abort();
        assert!(handle.task_handle.is_none());
    }

    #[tokio::test]
    async fn start_tui_returns_passive_handle() {
        let (action_tx, _action_rx) = mpsc::channel(32);
        let (event_tx, _) = broadcast::channel(64);

        let ap = AccessPoint::Tui { can_approve: true };
        let handle = start_access_point(&ap, action_tx, event_tx).await.unwrap();

        assert!(handle.task_handle.is_none()); // passive
        assert!(handle.config.can_approve());
    }

    #[tokio::test]
    async fn start_repl_returns_passive_handle() {
        let (action_tx, _action_rx) = mpsc::channel(32);
        let (event_tx, _) = broadcast::channel(64);

        let ap = AccessPoint::Repl { can_approve: false };
        let handle = start_access_point(&ap, action_tx, event_tx).await.unwrap();

        assert!(handle.task_handle.is_none());
        assert!(!handle.config.can_approve());
    }

    #[tokio::test]
    async fn start_in_process_returns_passive_handle() {
        let (action_tx, _action_rx) = mpsc::channel(32);
        let (event_tx, _) = broadcast::channel(64);

        let ap = AccessPoint::InProcess;
        let handle = start_access_point(&ap, action_tx, event_tx).await.unwrap();

        assert!(handle.task_handle.is_none());
    }

    #[tokio::test]
    async fn can_approve_propagates_through_handle() {
        let (action_tx, _action_rx) = mpsc::channel(32);
        let (event_tx, _) = broadcast::channel(64);

        let ap = AccessPoint::Grpc {
            addr: "127.0.0.1:0".parse().unwrap(),
            can_approve: true,
        };
        // Note: gRPC server start will likely fail to bind on port 0 in some envs,
        // but the handle is created before the server runs, so we test the config.
        let handle = start_access_point(&ap, action_tx, event_tx).await.unwrap();
        assert!(handle.config.can_approve());
        assert_eq!(handle.config.kind_label(), "gRPC");
    }

    #[tokio::test]
    async fn multiple_access_points_share_event_broadcast() {
        let (event_tx, _) = broadcast::channel::<EngineEvent>(64);

        // Simulate multiple access points subscribing
        let mut rx1 = event_tx.subscribe();
        let mut rx2 = event_tx.subscribe();
        let mut rx3 = event_tx.subscribe();

        // Gateway sends an event
        let _ = event_tx.send(EngineEvent::TextDelta {
            text: "broadcast_test".to_string(),
        });

        // All access points should receive it
        let e1 = rx1.recv().await.unwrap();
        let e2 = rx2.recv().await.unwrap();
        let e3 = rx3.recv().await.unwrap();

        assert!(matches!(e1, EngineEvent::TextDelta { text } if text == "broadcast_test"));
        assert!(matches!(e2, EngineEvent::TextDelta { text } if text == "broadcast_test"));
        assert!(matches!(e3, EngineEvent::TextDelta { text } if text == "broadcast_test"));
    }

    #[tokio::test]
    async fn multiple_access_points_merge_actions() {
        let (action_tx, mut action_rx) = mpsc::channel::<UserAction>(64);

        // Simulate 3 access points all holding clones of action_tx
        let tx1 = action_tx.clone();
        let tx2 = action_tx.clone();
        let tx3 = action_tx;

        tx1.send(UserAction::SendMessage {
            content: "from_tui".to_string(),
        })
        .await
        .unwrap();
        tx2.send(UserAction::SendMessage {
            content: "from_repl".to_string(),
        })
        .await
        .unwrap();
        tx3.send(UserAction::SendMessage {
            content: "from_grpc".to_string(),
        })
        .await
        .unwrap();

        // Gateway receives all 3 merged into a single stream
        let a1 = action_rx.recv().await.unwrap();
        let a2 = action_rx.recv().await.unwrap();
        let a3 = action_rx.recv().await.unwrap();

        assert_eq!(
            a1,
            UserAction::SendMessage {
                content: "from_tui".to_string()
            }
        );
        assert_eq!(
            a2,
            UserAction::SendMessage {
                content: "from_repl".to_string()
            }
        );
        assert_eq!(
            a3,
            UserAction::SendMessage {
                content: "from_grpc".to_string()
            }
        );
    }
}
