use tokio::sync::{broadcast, mpsc};

use crate::constants::engine::{ACTION_CHANNEL_BUFFER, EVENT_CHANNEL_BUFFER};
use crate::engine::events::{EngineEvent, UserAction};

/// Channel pair for communication between parent and child Agents.
///
/// Each parent-child relationship corresponds to a channel pair:
///   - Parent→Child: `mpsc<UserAction>` — Parent sends commands to child (Single Producer, Multiple Consumer)
///   - Child→Parent: `broadcast<EngineEvent>` — Events generated by child are broadcasted to parent and other subscribers
///
/// ```text
///   Parent (Master/Gateway)
///     │                     ▲
///     │ action_tx ──────►   │ event_tx.subscribe()
///     ▼                     │
///   Child (Worker/Master)
///     action_rx             event_tx
/// ```
pub struct ChannelPair {
    // ── Held by Parent (for sending commands to child) ──
    /// Parent→Child action sender. Cloning this sender allows multiple upstream sources to send commands to the child.
    pub action_tx: mpsc::Sender<UserAction>,

    // ── Held by Child (for receiving commands from parent) ──
    /// Parent→Child action receiver. Passed to the child's KezenEngine or AgentNode.
    pub action_rx: Option<mpsc::Receiver<UserAction>>,

    // ── Held by Child (for broadcasting events) ──
    /// Child→Parent event broadcast sender. Held by child, calls `send()` for every generated event.
    /// Parent obtains receiver via `event_tx.subscribe()`.
    pub event_tx: broadcast::Sender<EngineEvent>,
}

impl ChannelPair {
    /// Takes `action_rx` from the channel pair (can only be taken once).
    ///
    /// Used to pass the receiver end to the child's KezenEngine constructor—
    /// KezenEngine requires ownership of `mpsc::Receiver<UserAction>`.
    pub fn take_action_rx(&mut self) -> Option<mpsc::Receiver<UserAction>> {
        self.action_rx.take()
    }

    /// Creates a new subscriber for event broadcast.
    ///
    /// Parent node uses this method to subscribe to the event stream generated by the child node.
    /// Can be called multiple times—each returns an independent receiver.
    pub fn subscribe_events(&self) -> broadcast::Receiver<EngineEvent> {
        self.event_tx.subscribe()
    }
}

/// Creates a communication channel pair between Agents.
///
/// # Arguments
/// - `action_buffer` — Capacity of Parent→Child MPSC channel
/// - `event_buffer` — Capacity of Child→Parent broadcast channel
///
/// # Returns
/// A `ChannelPair` holding all channel ends.
pub fn create_agent_channel_pair(action_buffer: usize, event_buffer: usize) -> ChannelPair {
    let (action_tx, action_rx) = mpsc::channel(action_buffer);
    let (event_tx, _) = broadcast::channel(event_buffer);

    ChannelPair {
        action_tx,
        action_rx: Some(action_rx),
        event_tx,
    }
}

/// Creates a communication channel pair between Agents with default buffer sizes.
///
/// Default values:
/// - action buffer = `ACTION_CHANNEL_BUFFER` (32)
/// - event buffer = `EVENT_CHANNEL_BUFFER` (64)
pub fn create_default_channel_pair() -> ChannelPair {
    create_agent_channel_pair(ACTION_CHANNEL_BUFFER, EVENT_CHANNEL_BUFFER)
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── Channel message passing correctness ───────────────────────────────────────────

    #[tokio::test]
    async fn action_channel_send_receive() {
        let mut pair = create_default_channel_pair();
        let rx = pair.take_action_rx().unwrap();

        pair.action_tx
            .send(UserAction::SendMessage {
                content: "hello".to_string(),
            })
            .await
            .unwrap();

        // Use a oneshot-style receive to avoid blocking forever
        let mut rx = rx;
        let msg = rx.recv().await.unwrap();
        assert_eq!(
            msg,
            UserAction::SendMessage {
                content: "hello".to_string()
            }
        );
    }

    #[tokio::test]
    async fn event_broadcast_send_receive() {
        let pair = create_default_channel_pair();
        let mut rx = pair.subscribe_events();

        let _ = pair.event_tx.send(EngineEvent::Done);

        let evt = rx.recv().await.unwrap();
        assert!(matches!(evt, EngineEvent::Done));
    }

    // ── Channel close detection ────────────────────────────────────────────────

    #[tokio::test]
    async fn action_channel_sender_drop_closes_receiver() {
        let mut pair = create_default_channel_pair();
        let mut rx = pair.take_action_rx().unwrap();

        // Drop the sender: child's receiver should get None.
        drop(pair.action_tx);

        let result = rx.recv().await;
        assert!(
            result.is_none(),
            "Receiver should get None when sender is dropped"
        );
    }

    #[tokio::test]
    async fn event_broadcast_sender_drop_closes_receiver() {
        let pair = create_default_channel_pair();
        let mut rx = pair.subscribe_events();

        // Drop the sender
        drop(pair.event_tx);

        let result = rx.recv().await;
        assert!(
            result.is_err(),
            "Broadcast receiver should get Err when sender is dropped"
        );
    }

    // ── Broadcast multiple subscribers receive message simultaneously ──────────────────────────────────

    #[tokio::test]
    async fn broadcast_multiple_subscribers() {
        let pair = create_default_channel_pair();

        let mut rx1 = pair.subscribe_events();
        let mut rx2 = pair.subscribe_events();
        let mut rx3 = pair.subscribe_events();

        // Send one event
        let _ = pair.event_tx.send(EngineEvent::TextDelta {
            text: "shared".to_string(),
        });

        // All three subscribers should receive it
        let e1 = rx1.recv().await.unwrap();
        let e2 = rx2.recv().await.unwrap();
        let e3 = rx3.recv().await.unwrap();

        assert!(matches!(e1, EngineEvent::TextDelta { text } if text == "shared"));
        assert!(matches!(e2, EngineEvent::TextDelta { text } if text == "shared"));
        assert!(matches!(e3, EngineEvent::TextDelta { text } if text == "shared"));
    }

    // ── take_action_rx can only be taken once ──────────────────────────────────

    #[test]
    fn take_action_rx_returns_none_on_second_call() {
        let mut pair = create_default_channel_pair();
        assert!(pair.take_action_rx().is_some());
        assert!(pair.take_action_rx().is_none());
    }

    // ── Custom buffer size ──────────────────────────────────────────────

    #[tokio::test]
    async fn custom_buffer_sizes() {
        let mut pair = create_agent_channel_pair(4, 8);
        let mut rx = pair.take_action_rx().unwrap();

        // Fill up the action buffer (capacity 4)
        for i in 0..4 {
            pair.action_tx
                .send(UserAction::SendMessage {
                    content: format!("msg-{}", i),
                })
                .await
                .unwrap();
        }

        // Drain and verify order
        for i in 0..4 {
            let msg = rx.recv().await.unwrap();
            assert_eq!(
                msg,
                UserAction::SendMessage {
                    content: format!("msg-{}", i)
                }
            );
        }
    }
}
