use secrecy::SecretString;
use std::path::PathBuf;
use std::fs;

/// Get the path to the credentials file (~/.kezen/.credentials)
pub fn credentials_path() -> PathBuf {
    let kezen_home = dirs::home_dir()
        .expect("Cannot determine home directory")
        .join(".kezen");
    kezen_home.join(".credentials")
}

/// Retrieve a key from the .credentials file if it has the `keystore://` prefix.
pub fn resolve_key(raw_key: Option<String>) -> Option<SecretString> {
    let key = raw_key?;

    if key.starts_with("keystore://") {
        let identifier = key.strip_prefix("keystore://").unwrap();
        let cred_path = credentials_path();

        if !cred_path.exists() {
            eprintln!("  ⚠ [Keychain Error] No credentials file found. Please run `kezen keys set {} <API_KEY>`", identifier);
            return None;
        }

        let content = match fs::read_to_string(&cred_path) {
            Ok(c) => c,
            Err(e) => {
                eprintln!("  ⚠ [Keychain Error] Failed to read credentials file: {}", e);
                return None;
            }
        };

        // Parse key=value or basic TOML format manually for robustness
        for line in content.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            if let Some((k, v)) = line.split_once('=') {
                let k = k.trim().trim_matches('"').trim_matches('\'');
                if k == identifier {
                    let v = v.trim().trim_matches('"').trim_matches('\'');
                    return Some(SecretString::from(v));
                }
            }
        }
        
        eprintln!("  ⚠ [Keychain Error] Key '{}' not found in secure storage", identifier);
        None
    } else {
        Some(SecretString::from(key))
    }
}

/// Save a key into the .credentials file
pub fn set_key(profile: &str, key: &str) -> anyhow::Result<()> {
    use std::os::unix::fs::PermissionsExt;
    
    let cred_path = credentials_path();
    let mut keys = std::collections::HashMap::new();

    if cred_path.exists() {
        let content = fs::read_to_string(&cred_path)?;
        for line in content.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            if let Some((k, v)) = line.split_once('=') {
                let k = k.trim().trim_matches('"').trim_matches('\'');
                let v = v.trim().trim_matches('"').trim_matches('\'');
                keys.insert(k.to_string(), v.to_string());
            }
        }
    } else {
        // Ensure parent directory exists
        if let Some(parent) = cred_path.parent() {
            fs::create_dir_all(parent)?;
        }
    }

    // Insert or update
    keys.insert(profile.to_string(), key.to_string());

    // Serialize back
    let mut out = String::new();
    out.push_str("# KeZen Secure Credentials Store\n");
    out.push_str("# This file is automatically generated and uses 0600 privileges.\n\n");
    for (k, v) in keys {
        out.push_str(&format!("\"{}\" = \"{}\"\n", k, v));
    }

    fs::write(&cred_path, out)?;

    // Set 0600 permissions
    let mut perms = fs::metadata(&cred_path)?.permissions();
    perms.set_mode(0o600);
    fs::set_permissions(&cred_path, perms)?;

    Ok(())
}
